# Generated by Django 4.2.11 on 2024-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('token_number', models.CharField(max_length=100)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_Name',
            new_name='doctor_name',
        ),
    ]
