# Generated by Django 4.2.11 on 2024-04-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_rename_doctor_name_doctor_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('service_name', models.CharField(max_length=100)),
                ('treatment_cost', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('advance_paid', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('card_check_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(),
        ),
    ]
